config/routes.rb
SkAssetImages::Application.routes.draw do
	root to: 'galleries#index'
  resources :images
  resources :image_types

  resources :titles do
  	resources :images
  end
  resources :celebs do
  	resources :images
  end
end

app/models/celeb.rb
class Celeb < ActiveRecord::Base
  attr_accessible :name, :images_attributes
  attr_accessor :file
  has_many :images, as: :attachable
  has_and_belongs_to_many :image_types

  validates :name, presence: true, :uniqueness => {:case_sensitive => false}
  accepts_nested_attributes_for :images, allow_destroy: true

end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :attachable_id, :attachable_type, :name
  # attr_accessor :image, :file, :name
  attr_accessor :image, :file, :name, :crop_x, :crop_y, :crop_w, :crop_h
  belongs_to :attachable, polymorphic: true

  mount_uploader :name, ImageUploader
  # validates_processing_of :name
end

app/models/image_type.rb
class ImageType < ActiveRecord::Base
	# attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
	# after_update :crop_image_type

  attr_accessible :name
  has_and_belongs_to_many :celebs
  has_and_belongs_to_many :titles, :join_table => 'titles_image_types'
  validates :name, presence: true, :uniqueness => {:case_sensitive => false}
end

app/models/processed_image.rb
# class ProcessedImage < ActiveRecord::Base
#   belongs_to :asset_image
#   belongs_to :image_type
# end

app/models/title.rb
class Title < ActiveRecord::Base
  attr_accessible :name, :images_attributes
  attr_accessor :file
  has_many :images, as: :attachable
  has_and_belongs_to_many :image_types, :join_table => 'titles_image_types'

  validates :name, presence: true, :uniqueness => {:case_sensitive => false}
  accepts_nested_attributes_for :images, allow_destroy: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/celebs_controller.rb
class CelebsController < ApplicationController
  def index
    @celebs = Celeb.all
  end

  def show
    @celeb = Celeb.find(params[:id])
    @imageable = @celeb
    @images = @imageable.images
    @image = Image.new
  end

  def new
    @celeb = Celeb.new
    # @celeb.images.build
  end

  def create
    @celeb = Celeb.new(params[:celeb])
    if @celeb.save
      redirect_to @celeb, notice: "Successfully created celeb."
      # if params[:celeb][:image].present?
      #   render :crop
      # else
      #   redirect_to @celeb, notice: "Successfully created celeb."
      # end
    else
      render :new
    end
  end

  def edit
    @celeb = Celeb.find(params[:id])
  end

  def update
    @celeb = Celeb.find(params[:id])
    if @celeb.update_attributes(params[:celeb])
      # redirect_to @celeb, notice: "Successfully updated the celeb."
      if params[:celeb][:name].present?
        # @image_type = ImageType.new
        render :crop
      else
        redirect_to @celeb, notice: "Successfully updated celeb."
      end
    else
      render :edit
    end
  end

  def destroy
    @celeb = Celeb.find(params[:id])
    @celeb.destroy
    redirect_to titles_url, notice: "Successfully destroyed the title."
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
	def index
		@titles = Title.all
		@celebs = Celeb.all
	end
end

app/controllers/image_types_controller.rb
class ImageTypesController < ApplicationController

  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_filter :load_attachable

  def index
    @images = @attachable.images
  end

  def new
    @image = @attachable.images.new
  end

  def create
    @image = @attachable.images.new(params[:image])
    if @image.save
      redirect_to @attachable, notice: "Comment created."
    else
      render :new
    end
  end

  def edit
    @image = Image.find(params[:id])
  end

private

  def load_attachable
    resource, id = request.path.split('/')[1, 2] #/titles/1
    @attachable = resource.singularize.classify.constantize.find(id)
  end

  # alternative option:
  # def load_attachable
  #   klass = [Celeb, Title].detect { |c| params["#{c.name.underscore}_id"] }
  #   @attachable = klass.find(params["#{klass.name.underscore}_id"])
  # end
end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
  def index
    @titles = Title.all
  end

  def show
    @title = Title.find(params[:id])
    @imageable = @title
    @images = @imageable.images
    @image = Image.new
  end

  def new
    @title = Title.new
    #@title.images.build
  end

  def create
    @title = Title.new(params[:title])
    if @title.save
      redirect_to @title, notice: "Successfully created title."
      # if params[:title][:image].present?
      #   render :crop
      # else
      #   redirect_to @title, notice: "Successfully created title."
      # end
    else
      render :new
    end
  end

  def edit
    @title = Title.find(params[:id])
  end

  def update
    @title = Title.find(params[:id])
# binding.pry
    if @title.update_attributes(params[:title])
      redirect_to @title, notice: "Successfully updated the title."
      # if params[:title][:image].present?
      #   render :crop
      # else
      #   redirect_to @title, notice: "Successfully updated title."
      # end
    else
      render :edit
    end
  end

  def destroy
    @title = Title.find(params[:id])
    @title.destroy
    redirect_to titles_url, notice: "Successfully destroyed the title."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/celebs/_form.html.erb
<%= form_for @celeb, :html => {:multipart => true} do |f| %>
  <% if @celeb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@celeb.errors.count, "error") %> prohibited this celeb from being saved:</h2>
      <ul>
      <% @celeb.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label "Name" %>
    <%= f.text_field :name %>
    <br/>
    <%= f.fields_for :images do |ff| %>
      <%= ff.fields_for :image_type do |fff| %>
      <fieldset>
        <%= ff.label :name, "Image Name" %><br/>
        <%= ff.text_field :name %>
        <div class="thumb_image_container">
          <% @celeb.images.each do |img| %>
            <%= fff.label :name %>
            <%#= link_to image_tag(img.name.url(:thumb)), edit_celeb_path(@celeb) %>
            <%= link_to 'edit', edit_celeb_path(@celeb) %>

        </div>
        <div>
          <%= ff.label :name, "Upload New Celeb Image" %><br/>
          <%= ff.file_field :name %>
        </div>
        <fieldset>
            <!-- <h4>Image Type</h4> -->
            <h1>Crop & Set Image Type</h1>
            <%#= link_to image_tag(img.name), id: "cropbox" %>
            <%= image_tag(img.name) %>
            </div>

          <% end %>
        <% end %>
        </fieldset>
      </fieldset>

    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/celebs/_images.html.erb
<% @celeb.images.each do |img| %>
	<ul class="image_list_item">
		<div id="image_list_container">
			<li>
				<h4><%= img.name %></h4>
					<ul>
						<li class="no-bullet">
							<div id="model_images">
							<div class="thumb">
								<h4>Thumbnail</h4>
								<%= link_to image_tag(img.name.url(:thumb)), celeb_path(@celeb) %><br/>
							</div>
							<div class="biopic">
								<h4>Biopic</h4>
								<%= link_to image_tag(img.name.url(:biopic)), celeb_path(@celeb) %><br/>
							</div>
							<div class="headshot">
								<h4>Headshot</h4>
								<%= link_to image_tag(img.name.url(:headshot)), celeb_path(@celeb) %><br/>
							</div>
							<div class="boxcover">
								<h4>Boxcover</h4>
								<%= link_to image_tag(img.name.url(:boxcover)), celeb_path(@celeb) %><br/>
							</div>
							<div class="promo">
								<h4>Promo</h4>
								<%= link_to image_tag(img.name.url(:promo)), celeb_path(@celeb) %><br/>
							</div>
							<%= link_to 'edit', edit_celeb_path(@celeb) %>
						</div>
					</li>
				</ul>
			</li>
		</div>
	</ul>
<% end %>

app/views/celebs/_thumb_image.html.erb
<% @celebs.each do |celeb| %>
	<ul class="image_list_item">
		<div id="image_list_container">
			<li>
				<h4><%= celeb.name %></h4>
					<ul>
						<li class="no-bullet">
						<% celeb.images.each do |i| %>
							<div id="model_images">
								<%= link_to image_tag(i.name.url(:thumb)), celeb_path(celeb) %><br/>
								<%= link_to 'edit', edit_celeb_path(celeb) %>
								<!-- <span><%#= t.name.humanize %> | <%#= t.crop_x %> X <%#= t.crop_y %></span> -->
							</div>
						<% end %>
					</li>
				</ul>
			</li>
		</div>
	</ul>
<% end %>

app/views/celebs/crop.html.erb
<h1>Crop & Set Image Type</h1>
<%= image_tag @celeb.images.first.name, id: "cropbox" %>

<h4>Preview</h4>
<div style="width:100px; height:100px; overflow:hidden">
  <%= image_tag @celeb.images.first.name, :id => "preview" %>
</div>

<%= form_for @celeb.images.first do |f| %>
  <% %w[x y w h].each do |attribute| %>
    <%= f.hidden_field "crop_#{attribute}" %>
  <% end %>
<% end %>

app/views/celebs/edit.html.erb
<h1>Editing Celeb</h1>

<%= render 'form' %>

<%= link_to 'Show', @celeb %> |
<%= link_to 'Back', celebs_path %>

app/views/celebs/index.html.erb
	<h1>Celebs</h1>
	<%= render 'thumb_image' %>
	<div class="buttons-container">
		<div class="new-button">
			<%#= link_to "New Image", [:new, @attachable, :image], :class=> 'button radius' %>
			<%= link_to "New Celeb", new_celeb_path, :class=> 'button radius' %>
		</div>
		<div class="home-button">
			<%= link_to "Home", root_path, :class=> 'button radius' %>
		</div>
	</div>

app/views/celebs/new.html.erb
<h1>New Celeb</h1>
<%= render 'form' %>
<%= link_to 'All Celebs', celebs_path %>

app/views/celebs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h2>Name:<%= simple_format @celeb.name %></h2>
</p>
<%= link_to 'edit', edit_celeb_path(@celeb) %> |
<%= link_to "destroy", @celeb, method: :delete, confirm: "you sure?" %> |
<%= link_to 'all celebs', celebs_path %> |
<%= link_to 'home', root_path %>

<h2>Celeb Images</h2>

<%= render "images" %>

app/views/galleries/index.html.erb
<div id="titles">
	<h1>Titles</h1>
	<div><%= link_to "New Title", new_title_path, :class=> 'button radius' %></div>
	<%= render 'titles/thumb_image' %>
</div>

<div id="celebs">
	<h1>Celebs</h1>
	<div><%= link_to "New Celeb", new_celeb_path, :class=> 'button radius' %></div>
	<%= render 'celebs/thumb_image' %>
</div>
<fieldset>
	<h3>Image Types</h3>
</fieldset>

<div class="all-container">
	<div class="all-titles">
		<%= link_to "all titles", titles_path, :class=> 'button radius'  %>
	</div>
	<div class="all-celebs">
		<%= link_to "all celebs", celebs_path, :class=> 'button radius'  %>
	</div>
</div>

app/views/images/_form.html.erb
<%= form_for @attachable do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>
      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label "Image Name" %>
    <%= f.text_field :name %>
    <br/>
    <%= f.label :image, "Upload New Image" %>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/_images.html.erb
<% @images.each do |image| %>
	<ul class="image_list_item">
		<div id="image_list_container">
			<li>
				<h4><%= image.name %></h4>
				<%= link_to image_tag(image.name.url(:thumb)), edit_image_path(image) %>
				<%= link_to 'edit', edit_image_path(image) %>
			</li>
		</div>
	</ul>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<h4>Current Image</h4>
<div><%#= image_tag @image.asset_image.url(:thumb)%></div><br/>

<%= render 'form' %>

app/views/images/index.html.erb
<h1>Images</h1>
<div><%= render 'images' %></div>
<div class="buttons-container">
	<div class="new-button">
		<%= link_to "New Image", [:new, @attachable, :image], :class=> 'button radius' %>
	</div>
	<div class="home-button">
		<%= link_to "Home", root_path, :class=> 'button radius' %>
	</div>
</div>

app/views/images/new.html.erb
<h1>New Image</h1>
<%= render 'form' %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Image:</b><br/>
  <b><%= @image.name %></b>
  <%= link_to image_tag(@image.asset_image.url(:medium)), edit_image_path(@image) %>
</p>

<%= link_to 'edit', edit_image_path(@image) %>
<%= link_to "destroy", @image, method: :delete, confirm: "Are you sure?" %> |
<%= link_to 'all images', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />
  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="body-container">
      <%= yield %>
      <%= javascript_include_tag "application" %>
    </div>
  </body>
</html>

app/views/titles/_form.html.erb
<%= form_for @title, :html => {:multipart => true} do |f| %>
  <% if @title.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@title.errors.count, "error") %> prohibited this title from being saved:</h2>
      <ul>
      <% @title.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label "Name" %>
    <%= f.text_field :name %>
    <br/>
    <%= f.fields_for :images do |ff| %>
      <%= ff.fields_for :image_type do |fff| %>
      <fieldset>
        <%= ff.label :name, "Image Name" %><br/>
        <%= ff.text_field :name %>
        <h5>Image Type: <%#= @title.images.first.image_types.first.name %></h5>
        <div class="thumb_image_container">
          <% @title.images.each do |ai| %>
            <%= fff.label :name, @title.images.first.name %>
            <%= link_to image_tag(ai.name.url(:thumb)), edit_title_path(@title) %>
            <%= link_to 'edit', edit_title_path(@title) %>
          <% end %>
        </div>
        <%= ff.label :name, "Upload New Title Image" %><br/>
        <%= ff.file_field :name %>
        <fieldset>
            <h4>Image Type</h4>
            <%#= ff.fields_for :image_type do |fff| %>
            <%#= fff.label :name %>
            <%#= fff.text_field :name %>
            <%#= fff.label :crop_x %>
            <%#= fff.text_field :crop_x %>
            <%#= fff.label :crop_y %>
            <%#= fff.text_field :crop_y %>
          <% end %>
        </fieldset>
      </fieldset>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/titles/_images.html.erb
<% @title.images.each do |img| %>
	<ul class="image_list_item">
		<div id="image_list_container">
			<li>
				<h4><%= img.name %></h4>
					<ul>
						<li class="no-bullet">
							<div id="model_images">
							<div class="thumb">
								<h4>Thumbnail</h4>
								<%= link_to image_tag(img.name.url(:thumb)), title_path(@title) %><br/>
							</div>
							<div class="biopic">
								<h4>Biopic</h4>
								<%= link_to image_tag(img.name.url(:biopic)), title_path(@title) %><br/>
							</div>
							<div class="headshot">
								<h4>Headshot</h4>
								<%= link_to image_tag(img.name.url(:headshot)), title_path(@title) %><br/>
							</div>
							<div class="boxcover">
								<h4>Boxcover</h4>
								<%= link_to image_tag(img.name.url(:boxcover)), title_path(@title) %><br/>
							</div>
							<div class="promo">
								<h4>Promo</h4>
								<%= link_to image_tag(img.name.url(:promo)), title_path(@title) %><br/>
							</div>
							<%= link_to 'edit', edit_title_path(@title) %>
						</div>
					</li>
				</ul>
			</li>
		</div>
	</ul>
<% end %>

app/views/titles/_thumb_image.html.erb
<% @titles.each do |title| %>
	<ul class="image_list_item">
		<div id="image_list_container">
			<li>
				<h4><%= title.name %></h4>
					<ul>
						<li class="no-bullet">
						<% title.images.each do |i| %>
							<div id="model_images">
								<%= link_to image_tag(i.name.url(:thumb)), title_path(title) %><br/>
								<%= link_to 'edit', edit_title_path(title) %>
								<!-- <span><%#= t.name.humanize %> | <%#= t.crop_x %> X <%#= t.crop_y %></span> -->
							</div>
						<% end %>
					</li>
				</ul>
			</li>
		</div>
	</ul>
<% end %>

app/views/titles/edit.html.erb
<h1>Editing Title</h1>

<%= render 'form' %>

<%= link_to 'Show', @title %> |
<%= link_to 'Back', titles_path %>

app/views/titles/index.html.erb
<h1>Titles</h1>
<%= render 'thumb_image' %>
<div class="buttons-container">
	<div class="new-button">
		<%#= link_to "New Image", [:new, @attachable, :image], :class=> 'button radius' %>
		<%= link_to "New Title", new_title_path, :class=> 'button radius' %>
	</div>
	<div class="home-button">
		<%= link_to "Home", root_path, :class=> 'button radius' %>
	</div>
</div>

app/views/titles/new.html.erb
<h1>New Title</h1>
<%#= render 'form' %>
<%= link_to 'All Titles', titles_path %>

app/views/titles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h2>Name:<%= simple_format @title.name %></h2>
</p>
<%= link_to 'edit', edit_title_path(@title) %> |
<%= link_to "destroy", @title, method: :delete, confirm: "Are you sure?" %> |
<%= link_to 'all titles', titles_path %> |
<%= link_to 'home', root_path %>

<h2>Title Images</h2>

<%= render "images" %>